apiVersion: aws.platform.upbound.io/v1alpha1
kind: Network
metadata:
  name: configuration-aws-eks-pod-identity
  namespace: default
spec:
  parameters:
    id: configuration-aws-eks-pod-identity
    region: us-west-2
