apiVersion: aws.platform.upbound.io/v1alpha1
kind: XNetwork
metadata:
  name: configuration-aws-eks-pod-identity-kcl
spec:
  parameters:
    id: configuration-aws-eks-pod-identity-kcl
    region: us-west-2
