apiVersion: aws.platform.upbound.io/v1alpha1
kind: XPodIdentity
metadata:
  name: configuration-aws-eks-pod-identity-kcl
spec:
  compositionSelector:
    matchLabels:
      function: kcl
  parameters:
    region: us-west-2
    clusterNameSelector:
      matchLabels:
        crossplane.io/composite: configuration-aws-eks-pod-identity-kcl
    managedPolicyArns:
      - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
    inlinePolicy:
      - name: default
        policy: |
          {
              "Version": "2012-10-17",
              "Statement": [
                  {
                      "Action": [
                          "kms:Decrypt",
                          "kms:DescribeKey"
                      ],
                      "Effect": "Allow",
                      "Resource": "*"
                  }
              ]
          }
    serviceAccount:
      name: my-controller
      namespace: kube-system
