apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xpodidentities.aws.platform.upbound.io
spec:
  compositeTypeRef:
    apiVersion: aws.platform.upbound.io/v1alpha1
    kind: XPodIdentity
  mode: Pipeline
  pipeline:
  - functionRef:
      name: upbound-configuration-aws-eks-pod-identityeks-pod-identity
    step: eks-pod-identity
  - functionRef:
      name: crossplane-contrib-function-auto-ready
    step: crossplane-contrib-function-auto-ready
