apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xpodidentities.aws.platform.upbound.io
  labels:
    provider: aws
spec:
  defaultCompositionRef:
    name: pat.xpodidentities.aws.platform.upbound.io
  group: aws.platform.upbound.io
  names:
    kind: XPodIdentity
    plural: xpodidentities
  claimNames:
    kind: PodIdentity
    plural: podidentities
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  description: PodIdentity configuration parameters.
                  properties:
                    region:
                      type: string
                      description: Region is the region your cluster is running in.
                    clusterName:
                      description: The name of the cluster to create the association
                        in.
                      type: string
                    clusterNameRef:
                      description: Reference to a Cluster in eks to populate clusterName.
                      properties:
                        name:
                          description: Name of the referenced object.
                          type: string
                        policy:
                          description: Policies for referencing.
                          properties:
                            resolution:
                              default: Required
                              description: |-
                                Resolution specifies whether resolution of this reference is required.
                                The default is 'Required', which means the reconcile will fail if the
                                reference cannot be resolved. 'Optional' means this reference will be
                                a no-op if it cannot be resolved.
                              enum:
                                - Required
                                - Optional
                              type: string
                            resolve:
                              description: |-
                                Resolve specifies when this reference should be resolved. The default
                                is 'IfNotPresent', which will attempt to resolve the reference only when
                                the corresponding field is not present. Use 'Always' to resolve the
                                reference on every reconcile.
                              enum:
                                - Always
                                - IfNotPresent
                              type: string
                          type: object
                      required:
                        - name
                      type: object
                    clusterNameSelector:
                      description: Selector for a Cluster in eks to populate clusterName.
                      properties:
                        matchControllerRef:
                          description: |-
                            MatchControllerRef ensures an object with the same controller reference
                            as the selecting object is selected.
                          type: boolean
                        matchLabels:
                          additionalProperties:
                            type: string
                          description: MatchLabels ensures an object with matching labels
                            is selected.
                          type: object
                        policy:
                          description: Policies for selection.
                          properties:
                            resolution:
                              default: Required
                              description: |-
                                Resolution specifies whether resolution of this reference is required.
                                The default is 'Required', which means the reconcile will fail if the
                                reference cannot be resolved. 'Optional' means this reference will be
                                a no-op if it cannot be resolved.
                              enum:
                                - Required
                                - Optional
                              type: string
                            resolve:
                              description: |-
                                Resolve specifies when this reference should be resolved. The default
                                is 'IfNotPresent', which will attempt to resolve the reference only when
                                the corresponding field is not present. Use 'Always' to resolve the
                                reference on every reconcile.
                              enum:
                                - Always
                                - IfNotPresent
                              type: string
                          type: object
                      type: object
                    inlinePolicy:
                      description: Configuration block defining an exclusive set of
                        IAM inline policies associated with the IAM role. See below.
                        If no blocks are configured, Crossplane will not manage any
                        inline policies in this resource. Configuring one empty block
                        (i.e., inline_policy {}) will cause Crossplane to remove all
                        inline policies added out of band on apply.
                      items:
                        properties:
                          name:
                            description: Friendly name of the role. See IAM Identifiers
                              for more information.
                            type: string
                          policy:
                            description: Policy document as a JSON formatted string.
                            type: string
                        type: object
                      type: array
                    managedPolicyArns:
                      description: Set of exclusive IAM managed policy ARNs to attach
                        to the IAM role. If this attribute is not configured, Crossplane
                        will ignore policy attachments to this resource. When configured,
                        Crossplane will align the role's managed policy attachments
                        with this set by attaching or detaching managed policies. Configuring
                        an empty set (i.e., managed_policy_arns = []) will cause Crossplane
                        to remove all managed policy attachments.
                      items:
                        type: string
                      type: array
                      x-kubernetes-list-type: set
                    deletionPolicy:
                      description: Delete the external resources when the Claim/XR is deleted. Defaults to Delete
                      enum:
                        - Delete
                        - Orphan
                      type: string
                      default: Delete
                    providerConfigName:
                      description: Crossplane ProviderConfig to use for provisioning this resources
                      type: string
                      default: default
                    serviceAccount:
                      type: object
                      description: Configuration for SA
                      properties:
                        name:
                          type: string
                          description: name kubernetes SA
                        namespace:
                          type: string
                          description: namespace kubernetes SA
                      required:
                        - name
                        - namespace
                  required:
                    - serviceAccount
              required:
                - parameters
            status:
              type: object
              properties:
                podIdentity:
                  description: Freeform field containing status information for podidentity
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
